spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/event_db
    username: event
    password: event
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true

aws:
  region: sa-east-1
  bucket:
    name: eventostec-svt2-imgs